version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "20:00"
  pull-request-branch-name:
    separator: "-"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sharp
    versions:
    - 0.27.1
    - 0.27.2
    - 0.28.0
  - dependency-name: "@google-cloud/storage"
    versions:
    - 5.7.3
    - 5.7.4
    - 5.8.0
    - 5.8.1
    - 5.8.2
    - 5.8.3
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: handlebars
    versions:
    - 4.7.6
