steps:
  - name: node:13.7.0-alpine
    entrypoint: sh
    args:
      - -c
      - |
        yarn
        yarn test
  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud kms decrypt --ciphertext-file=.env.${_TARGET_ENV}.yaml.enc --plaintext-file=.env.yaml --location=global --keyring=qoodish --key=qoodish
        gcloud functions deploy generateThumbnails --trigger-resource ${_BUCKET_NAME} --trigger-event google.storage.object.finalize --runtime nodejs10 --memory 2048MB --region asia-northeast1
        gcloud functions deploy notifyFeedback --trigger-event providers/cloud.firestore/eventTypes/document.create --trigger-resource projects/$PROJECT_ID/databases/default/documents/feedbacks/{feedbackId} --runtime nodejs10 --region asia-northeast1 --env-vars-file .env.yaml
